#  Copyright (c) VKU.NewEnergy.

#  This source code is licensed under the Apache-2.0 license found in the
#  LICENSE file in the root directory of this source tree.

FROM postgres:14
COPY create-multiple-postgresql-databases.sh /docker-entrypoint-initdb.d/